name: Terraform destroy quick

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to continue proceed"
        required: true

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  terraform-plan:
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838
        with:
          role-to-assume: arn:aws:iam::625715126488:role/GithubActions
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: "1.5.5"
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
      
      - name: Terraform Destroy
        run: terraform destroy -auto-approve